// ==============================================================================
// 🎮 LaraQuest Constants & Game Mechanics
// ==============================================================================

export const LEVELS = [
  { level: 1, name: 'Hello, Artisan', minXp: 0, maxXp: 100, badge: '🌱', color: '#10b981' },
  { level: 2, name: 'Route Rookie', minXp: 100, maxXp: 300, badge: '🧭', color: '#06b6d4' },
  { level: 3, name: 'Controller Cadet', minXp: 300, maxXp: 600, badge: '🎮', color: '#3b82f6' },
  { level: 4, name: 'Migration Master', minXp: 600, maxXp: 1000, badge: '🗄️', color: '#6366f1' },
  { level: 5, name: 'Eloquent Explorer', minXp: 1000, maxXp: 1500, badge: '✨', color: '#8b5cf6' },
  { level: 6, name: 'Middleware Maven', minXp: 1500, maxXp: 2100, badge: '🛡️', color: '#ec4899' },
  { level: 7, name: 'Auth Architect', minXp: 2100, maxXp: 2800, badge: '🔐', color: '#f43f5e' },
  { level: 8, name: 'API Artisan', minXp: 2800, maxXp: 3600, badge: '🌐', color: '#f59e0b' },
  { level: 9, name: 'Testing Titan', minXp: 3600, maxXp: 4500, badge: '🧪', color: '#eab308' },
  { level: 10, name: 'Full-Stack Falcon', minXp: 4500, maxXp: 6000, badge: '🦅', color: '#14b8a6' },
];

export const calculateLevel = (xp = 0) => {
  for (let i = LEVELS.length - 1; i >= 0; i--) {
    if (xp >= LEVELS[i].minXp) {
      const current = LEVELS[i];
      const next = LEVELS[i + 1] || null;
      const progressInLevel = next
        ? Math.min(100, Math.round(((xp - current.minXp) / (next.minXp - current.minXp)) * 100))
        : 100;
      const xpNeeded = next ? next.minXp - xp : 0;
      return {
        ...current,
        nextLevel: next,
        progressInLevel,
        xpNeeded,
      };
    }
  }
  return {
    ...LEVELS[0],
    nextLevel: LEVELS[1],
    progressInLevel: 0,
    xpNeeded: 100,
  };
};

export const INITIAL_MODULES = [
  {
    id: 1,
    orderIndex: 0,
    title: 'The Big Picture',
    subtitle: 'Connecting Flutter to the Server',
    description: 'What happens after Dio.get() sends a request? Unravel the server request-response lifecycle and understand MVC from a Flutter state perspective.',
    icon: '🗺️',
    gradient: 'from-blue-500 to-indigo-600',
    colorAccent: '#3b82f6',
    totalLessons: 4,
    estimatedMinutes: 15,
    flutterConnection: 'Think of the server as the unseen mirror of your Dio/Http client and Riverpod state.',
    lessons: [
      { id: 101, title: 'What happens after your Flutter app fires an API call?', xp: 25, duration: '4 min' },
      { id: 102, title: 'Client vs Server: Who is responsible for what?', xp: 25, duration: '3 min' },
      { id: 103, title: 'What is Laravel and why do mobile devs love it?', xp: 25, duration: '4 min' },
      { id: 104, title: 'The MVC Pattern: Flutter widgets vs Server architecture', xp: 35, duration: '5 min' },
    ],
  },
  {
    id: 2,
    orderIndex: 1,
    title: 'PHP Crash Course for Dart Devs',
    subtitle: 'Dart syntax meets modern PHP 8+',
    description: 'You already understand types, classes, functions, and async in Dart. Learn PHP 8 fast by looking at direct side-by-side comparisons.',
    icon: '🐘',
    gradient: 'from-purple-500 to-violet-600',
    colorAccent: '#8b5cf6',
    totalLessons: 4,
    estimatedMinutes: 20,
    flutterConnection: 'Dart `List<Map>` becomes PHP associative arrays; Dart classes translate into PHP classes with clean type hinting.',
    lessons: [
      { id: 201, title: 'Variables, Types, and Arrow Syntax ($var vs var)', xp: 25, duration: '4 min' },
      { id: 202, title: 'Arrays & Collections: List vs Associative Arrays', xp: 25, duration: '5 min' },
      { id: 203, title: 'OOP & Methods: Constructors and Property Promotion', xp: 30, duration: '5 min' },
      { id: 204, title: 'Namespaces & Autoloading: Dart `import` vs PHP `use`', xp: 30, duration: '4 min' },
    ],
  },
  {
    id: 3,
    orderIndex: 2,
    title: 'Laravel Setup & Artisan',
    subtitle: 'Like `flutter create` for Backends',
    description: 'Scaffold your project, tour the directory layout, and master the Artisan CLI companion that eliminates repetitive boilerplate.',
    icon: '🏗️',
    gradient: 'from-rose-500 to-red-600',
    colorAccent: '#ef4444',
    totalLessons: 4,
    estimatedMinutes: 20,
    flutterConnection: '`php artisan make:controller` is like Flutter code-gen (`build_runner`), but runs in 50 milliseconds.',
    lessons: [
      { id: 301, title: 'Composer & Project Anatomy: pubspec.yaml vs composer.json', xp: 25, duration: '4 min' },
      { id: 302, title: 'Where do files live? Flutter lib/ vs Laravel app/', xp: 25, duration: '5 min' },
      { id: 303, title: 'Mastering Artisan: The Flutter CLI equivalent', xp: 30, duration: '5 min' },
      { id: 304, title: 'Environment Config: .env vs flutter_dotenv', xp: 25, duration: '4 min' },
    ],
  },
  {
    id: 4,
    orderIndex: 3,
    title: 'Routing & Endpoints',
    subtitle: 'Where URLs Meet Executable Code',
    description: 'Map RESTful HTTP verbs (GET, POST, PUT, DELETE) and bind dynamic URL query params and route variables directly to controllers.',
    icon: '🛣️',
    gradient: 'from-amber-500 to-orange-600',
    colorAccent: '#f59e0b',
    totalLessons: 5,
    estimatedMinutes: 25,
    flutterConnection: 'The routes you declare in Laravel are the exact strings you pass into `dio.get("/api/v1/posts")`.',
    lessons: [
      { id: 401, title: 'The api.php Route File: Exposing endpoints', xp: 25, duration: '4 min' },
      { id: 402, title: 'HTTP Verbs: GET, POST, PUT, PATCH, DELETE', xp: 25, duration: '5 min' },
      { id: 403, title: 'Route Parameters & Constraints: /users/{id}', xp: 30, duration: '5 min' },
      { id: 404, title: 'Route Groups, Prefixes, and API Versioning', xp: 30, duration: '5 min' },
      { id: 405, title: 'Resource Routing: Instant REST endpoints', xp: 35, duration: '5 min' },
    ],
  },
  {
    id: 5,
    orderIndex: 4,
    title: 'Controllers & Responses',
    subtitle: 'The Brain of Your API',
    description: 'Handle incoming requests, execute business logic, and serialize formatted JSON responses that your Flutter models will parse cleanly.',
    icon: '🎮',
    gradient: 'from-emerald-500 to-teal-600',
    colorAccent: '#10b981',
    totalLessons: 5,
    estimatedMinutes: 25,
    flutterConnection: 'Controllers are like your Bloc/Notifier methods responding to events and emitting state.',
    lessons: [
      { id: 501, title: 'Single Action vs Resource Controllers', xp: 25, duration: '4 min' },
      { id: 502, title: 'Returning JSON: response()->json() vs jsonEncode', xp: 30, duration: '5 min' },
      { id: 503, title: 'HTTP Status Codes for Flutter Developers (200, 201, 400, 404, 422, 500)', xp: 30, duration: '5 min' },
      { id: 504, title: 'Dependency Injection: Provider/GetIt vs Laravel Service Container', xp: 35, duration: '5 min' },
      { id: 505, title: 'Building a complete Tasks CRUD controller', xp: 40, duration: '6 min' },
    ],
  },
  {
    id: 6,
    orderIndex: 5,
    title: 'Database & Migrations',
    subtitle: 'The Scary Part Made Intuitive',
    description: 'Visual database design, foreign keys, and version-controlled schemas. Build confidence with tables, rows, and relationships.',
    icon: '🗄️',
    gradient: 'from-pink-500 to-rose-600',
    colorAccent: '#ec4899',
    totalLessons: 6,
    estimatedMinutes: 35,
    flutterConnection: 'Stop wondering where data lives. Design database tables just like you design Flutter model classes.',
    lessons: [
      { id: 601, title: 'Relational Database Fundamentals: Tables, Primary & Foreign Keys', xp: 25, duration: '5 min' },
      { id: 602, title: 'Relationships Visualized: 1:1, 1:Many, and Many:Many', xp: 30, duration: '6 min' },
      { id: 603, title: 'Database Migrations: Git version control for your database', xp: 30, duration: '5 min' },
      { id: 604, title: 'Writing migration schema columns (strings, booleans, timestamps)', xp: 30, duration: '5 min' },
      { id: 605, title: 'Seeders and Model Factories: Generating fake test data', xp: 30, duration: '5 min' },
      { id: 606, title: 'Interactive Challenge: Design a Blog Database Schema', xp: 45, duration: '8 min' },
    ],
  },
  {
    id: 7,
    orderIndex: 6,
    title: 'Eloquent ORM',
    subtitle: 'Database Queries Made Beautiful',
    description: 'Write elegant, fluent database queries without typing raw SQL. Fetch relationships with eager loading and eliminate N+1 latency.',
    icon: '✨',
    gradient: 'from-cyan-500 to-blue-600',
    colorAccent: '#06b6d4',
    totalLessons: 6,
    estimatedMinutes: 30,
    flutterConnection: '`User::with("posts")->find(1)` gives you the nested JSON tree your Flutter UI widget expects.',
    lessons: [
      { id: 701, title: 'Eloquent Models: Mapping classes to database tables', xp: 25, duration: '4 min' },
      { id: 702, title: 'Querying: all(), find(), where(), and first()', xp: 30, duration: '5 min' },
      { id: 703, title: 'Relationships in Code: hasMany() and belongsTo()', xp: 35, duration: '6 min' },
      { id: 704, title: 'The N+1 Query Problem: Why Flutter devs must know eager loading', xp: 35, duration: '6 min' },
      { id: 705, title: 'Mutators, Accessors, and Casts: Dart getters vs Eloquent casts', xp: 30, duration: '5 min' },
      { id: 706, title: 'Eloquent Scopes: Reusable query filters', xp: 35, duration: '5 min' },
    ],
  },
  {
    id: 8,
    orderIndex: 7,
    title: 'Requests & Validation',
    subtitle: 'The Bulletproof Gatekeeper',
    description: 'Validate request bodies before they reach business logic. Generate clear 422 JSON validation errors that your Flutter forms can display.',
    icon: '📬',
    gradient: 'from-lime-500 to-green-600',
    colorAccent: '#84cc16',
    totalLessons: 5,
    estimatedMinutes: 25,
    flutterConnection: 'Your Flutter form validator protects the user experience; Laravel validation protects your database from corruption.',
    lessons: [
      { id: 801, title: 'Reading JSON payloads from $request', xp: 25, duration: '4 min' },
      { id: 802, title: 'Validation Rules: required, email, min, exists, unique', xp: 30, duration: '5 min' },
      { id: 803, title: 'Dedicated Form Request classes', xp: 35, duration: '5 min' },
      { id: 804, title: 'Custom Error Messages & JSON 422 Error Anatomy', xp: 30, duration: '5 min' },
      { id: 805, title: 'Challenge: Secure a User Registration Endpoint', xp: 40, duration: '6 min' },
    ],
  },
  {
    id: 9,
    orderIndex: 8,
    title: 'Authentication & Sanctum',
    subtitle: 'Tokens, Bearers & Middleware',
    description: 'Learn how API tokens are issued, verified, stored, and revoked. Protect sensitive endpoints using authentication middleware.',
    icon: '🔐',
    gradient: 'from-indigo-500 to-purple-600',
    colorAccent: '#6366f1',
    totalLessons: 5,
    estimatedMinutes: 30,
    flutterConnection: 'The Bearer token stored in flutter_secure_storage is minted and validated right here.',
    lessons: [
      { id: 901, title: 'How Token Authentication Works (Stateless APIs)', xp: 25, duration: '5 min' },
      { id: 902, title: 'Laravel Sanctum: Issuing mobile API tokens', xp: 35, duration: '6 min' },
      { id: 903, title: 'Middleware: The bouncer checking your Authorization header', xp: 30, duration: '5 min' },
      { id: 904, title: 'Securing routes with auth:sanctum', xp: 30, duration: '5 min' },
      { id: 905, title: 'Handling Logout & Revoking Tokens', xp: 30, duration: '4 min' },
    ],
  },
  {
    id: 10,
    orderIndex: 9,
    title: 'Building RESTful APIs',
    subtitle: 'The Grand Full-Stack Connection',
    description: 'API Resources for clean JSON data shaping, cursor and length-aware pagination, file uploads with multipart forms, and rate limiting.',
    icon: '🌐',
    gradient: 'from-teal-500 to-emerald-600',
    colorAccent: '#14b8a6',
    totalLessons: 6,
    estimatedMinutes: 35,
    flutterConnection: 'Design the exact backend endpoint contract that makes your Flutter Riverpod/Dio code clean and painless.',
    lessons: [
      { id: 1001, title: 'API Resource Classes: Shaping clean JSON output', xp: 30, duration: '5 min' },
      { id: 1002, title: 'Pagination for Mobile: cursorPaginate() vs ListView.builder', xp: 35, duration: '6 min' },
      { id: 1003, title: 'File & Image Uploads: Dio FormData vs $request->file()', xp: 35, duration: '6 min' },
      { id: 1004, title: 'Rate Limiting (Throttling) to protect against mobile spam', xp: 30, duration: '4 min' },
      { id: 1005, title: 'Standardized API Response Wrappers (data, message, status)', xp: 35, duration: '5 min' },
      { id: 1006, title: 'Challenge: Build a full Notes API for a Flutter app', xp: 45, duration: '8 min' },
    ],
  },
  {
    id: 11,
    orderIndex: 10,
    title: 'Testing Your API',
    subtitle: 'Confidence Before Deployment',
    description: 'Write automated feature tests using Laravel PEST and PHPUnit to verify that endpoints always return expected status codes and JSON schemas.',
    icon: '🧪',
    gradient: 'from-purple-500 to-pink-600',
    colorAccent: '#a855f7',
    totalLessons: 4,
    estimatedMinutes: 20,
    flutterConnection: 'Like Flutter integration tests, but testing HTTP responses, database records, and status codes in milliseconds.',
    lessons: [
      { id: 1101, title: 'Why Test APIs? Catch breaking changes before the Flutter app crashes', xp: 25, duration: '4 min' },
      { id: 1102, title: 'Writing Your First Feature Test: getJson() & assertOk()', xp: 35, duration: '5 min' },
      { id: 1103, title: 'Testing with RefreshDatabase & Factories', xp: 35, duration: '5 min' },
      { id: 1104, title: 'Testing Authentication & Protected Routes', xp: 35, duration: '5 min' },
    ],
  },
  {
    id: 12,
    orderIndex: 11,
    title: 'Final Capstone Project',
    subtitle: 'From Dart to Full-Stack Master',
    description: 'Synthesize everything you have learned: design database schemas, configure Eloquent models, establish routes, and provide auth.',
    icon: '🚀',
    gradient: 'from-rose-500 to-amber-600',
    colorAccent: '#f43f5e',
    totalLessons: 7,
    estimatedMinutes: 45,
    flutterConnection: 'You now build both ends of the bridge — the mobile Flutter UI and the powerful Laravel backend.',
    lessons: [
      { id: 1201, title: 'Project Spec & Architecture Blueprint', xp: 30, duration: '5 min' },
      { id: 1202, title: 'Database Schema & Migration Crafting', xp: 40, duration: '7 min' },
      { id: 1203, title: 'Models & Eloquent Relationships', xp: 40, duration: '7 min' },
      { id: 1204, title: 'Authentication & Sanctum Setup', xp: 40, duration: '6 min' },
      { id: 1205, title: 'API Resource Endpoints & Pagination', xp: 45, duration: '8 min' },
      { id: 1206, title: 'Comprehensive API Feature Tests', xp: 40, duration: '6 min' },
      { id: 1207, title: 'Graduation & Full-Stack Falcon Certification', xp: 100, duration: '5 min' },
    ],
  },
  {
    id: 13,
    orderIndex: 12,
    title: 'File Uploads & S3 Cloud Storage',
    subtitle: 'Handle Multipart Media Like a Pro',
    description: 'Validate binary image uploads, generate signed URLs, and stream media to Amazon S3 or Cloudflare R2 storage disks.',
    icon: '☁️',
    gradient: 'from-teal-500 to-emerald-600',
    colorAccent: '#14b8a6',
    totalLessons: 4,
    estimatedMinutes: 20,
    flutterConnection: 'Uploading avatars from Flutter ImagePicker requires multipart/form-data. Laravel Storage disk abstractions make cloud sync seamless.',
    lessons: [
      { id: 1301, title: 'Multipart Form Data & File Validation (mimes, max size)', xp: 25, duration: '5 min' },
      { id: 1302, title: 'Storage Disks: Local vs Public vs Amazon S3 / R2', xp: 30, duration: '5 min' },
      { id: 1303, title: 'Temporary Signed URLs for Secure Mobile Media Access', xp: 30, duration: '5 min' },
      { id: 1304, title: 'Image Resizing & Thumbnail Optimization Pipelines', xp: 35, duration: '5 min' },
    ],
  },
  {
    id: 14,
    orderIndex: 13,
    title: 'Queues, Jobs & Async Processing',
    subtitle: 'Never Keep the Mobile User Waiting',
    description: 'Offload heavy workloads to background Redis workers. Dispatch asynchronous jobs, handle retries, and monitor failed tasks.',
    icon: '⚡',
    gradient: 'from-blue-500 to-indigo-600',
    colorAccent: '#3b82f6',
    totalLessons: 4,
    estimatedMinutes: 20,
    flutterConnection: 'Keep mobile response times under 50ms by offloading email sending and push notifications to background workers.',
    lessons: [
      { id: 1401, title: 'Why Queues Matter for Mobile Backends (50ms response goals)', xp: 25, duration: '4 min' },
      { id: 1402, title: 'Writing & Dispatching Queue Jobs (implements ShouldQueue)', xp: 35, duration: '5 min' },
      { id: 1403, title: 'Job Retries, Exponential Backoff, and Dead Letter Queues', xp: 30, duration: '5 min' },
      { id: 1404, title: 'Running Queue Workers with Supervisor & Laravel Horizon', xp: 35, duration: '6 min' },
    ],
  },
  {
    id: 15,
    orderIndex: 14,
    title: 'Redis Caching & API Rate Limiting',
    subtitle: 'Sub-Millisecond Performance at Scale',
    description: 'Supercharge read-heavy endpoints with Redis caching, cache tagging, and prevent DDoS abuse with custom rate limiters.',
    icon: '🏎️',
    gradient: 'from-cyan-500 to-blue-600',
    colorAccent: '#06b6d4',
    totalLessons: 4,
    estimatedMinutes: 20,
    flutterConnection: 'Cache-Aside pattern in Redis is identical to Flutter Repository pattern checking Hive cache before calling Dio.',
    lessons: [
      { id: 1501, title: 'The Cache-Aside Pattern with Redis', xp: 25, duration: '4 min' },
      { id: 1502, title: 'Cache Invalidation Strategies & Cache Tags', xp: 30, duration: '5 min' },
      { id: 1503, title: 'Rate Limiting & Throttle Middleware (429 Too Many Requests)', xp: 30, duration: '5 min' },
      { id: 1504, title: 'Custom Dynamic Rate Limiters by User Tier', xp: 35, duration: '6 min' },
    ],
  },
  {
    id: 16,
    orderIndex: 15,
    title: 'Automated API Testing & MiniGram Capstone',
    subtitle: 'Deploy to Production with 100% Confidence',
    description: 'Write automated Pest/PHPUnit feature tests, generate OpenAPI documentation, and review the MiniGram Capstone API.',
    icon: '🎯',
    gradient: 'from-emerald-500 to-teal-600',
    colorAccent: '#10b981',
    totalLessons: 4,
    estimatedMinutes: 25,
    flutterConnection: 'Automated API tests ensure your backend never breaks Flutter data parsers when updating endpoints.',
    lessons: [
      { id: 1601, title: 'Testing REST Endpoints with Pest / PHPUnit', xp: 30, duration: '6 min' },
      { id: 1602, title: 'Database Isolation with RefreshDatabase & Factories', xp: 35, duration: '6 min' },
      { id: 1603, title: 'Testing Authentication & Role Boundaries', xp: 30, duration: '5 min' },
      { id: 1604, title: 'OpenAPI / Swagger Documentation for Mobile Clients', xp: 35, duration: '6 min' },
    ],
  },
  {
    id: 17,
    orderIndex: 16,
    title: 'Service Layer & Repository Pattern',
    subtitle: 'Clean Architecture for Enterprise APIs',
    description: 'Decouple controllers from persistence with domain services, repository interfaces, single-responsibility actions, and typed DTOs.',
    icon: '🏗️',
    gradient: 'from-amber-500 to-yellow-600',
    colorAccent: '#fbbf24',
    totalLessons: 4,
    estimatedMinutes: 25,
    flutterConnection: 'Extracting logic from Controllers into Services is identical to extracting logic from StatefulWidgets into BLoCs and UseCases.',
    lessons: [
      { id: 1701, title: 'Fat Controllers = Fat Problems (Bloated BLoC vs Service Layer)', xp: 25, duration: '6 min' },
      { id: 1702, title: 'The Repository Pattern for Data Access', xp: 30, duration: '6 min' },
      { id: 1703, title: 'Single-Responsibility Action Classes', xp: 25, duration: '5 min' },
      { id: 1704, title: 'Data Transfer Objects (DTOs)', xp: 30, duration: '6 min' },
    ],
  },
  {
    id: 18,
    orderIndex: 17,
    title: 'Events, Listeners & Observers',
    subtitle: 'Decouple Side-Effects & Async Workflows',
    description: 'Hook into Eloquent model lifecycles, publish domain events, offload slow emails to background Redis workers, and explore Event Sourcing.',
    icon: '⚡',
    gradient: 'from-yellow-500 to-amber-600',
    colorAccent: '#f59e0b',
    totalLessons: 4,
    estimatedMinutes: 25,
    flutterConnection: 'Event dispatching in Laravel works just like Dart EventBus or Bloc Events, freeing the main thread from blocking side-effects.',
    lessons: [
      { id: 1801, title: 'Eloquent Model Observers', xp: 25, duration: '5 min' },
      { id: 1802, title: 'Events & Listeners: Decoupling Side-Effects', xp: 30, duration: '6 min' },
      { id: 1803, title: 'Asynchronous Queued Event Listeners', xp: 25, duration: '5 min' },
      { id: 1804, title: 'Event Sourcing & CQRS Mental Models', xp: 30, duration: '6 min' },
    ],
  },
  {
    id: 19,
    orderIndex: 18,
    title: 'Policies & RBAC Authorization',
    subtitle: 'Fine-Grained Permissions & Token Scopes',
    description: 'Separate 401 unauthenticated from 403 forbidden. Write model policies, implement Spatie roles & permissions, and restrict Sanctum tokens.',
    icon: '🛡️',
    gradient: 'from-amber-600 to-orange-600',
    colorAccent: '#d97706',
    totalLessons: 4,
    estimatedMinutes: 25,
    flutterConnection: 'Never trust client-side UI hiding! Server-side Policies enforce security rules regardless of how the request is dispatched.',
    lessons: [
      { id: 1901, title: 'Authentication vs Authorization (401 vs 403)', xp: 25, duration: '5 min' },
      { id: 1902, title: 'Writing Model Policy Classes', xp: 30, duration: '6 min' },
      { id: 1903, title: 'Role-Based Access Control (RBAC) with Spatie', xp: 25, duration: '6 min' },
      { id: 1904, title: 'Combining Sanctum Token Abilities with Policies', xp: 30, duration: '6 min' },
    ],
  },
  {
    id: 20,
    orderIndex: 19,
    title: 'Global Error Handling & Logging',
    subtitle: 'Production Observability & Zero Silent Failures',
    description: 'Create self-rendering domain exceptions, configure Laravel 11 bootstrap exception routing, write structured JSON logs, and monitor in Sentry.',
    icon: '🐞',
    gradient: 'from-orange-500 to-rose-600',
    colorAccent: '#ea580c',
    totalLessons: 4,
    estimatedMinutes: 25,
    flutterConnection: 'Guaranteeing your Laravel API always returns JSON envelopes ensures your Flutter Dio parsers never crash on 500 HTML pages.',
    lessons: [
      { id: 2001, title: 'Domain-Specific Custom Exception Classes', xp: 25, duration: '5 min' },
      { id: 2002, title: 'Laravel 11 Global Exception Handler (bootstrap/app.php)', xp: 30, duration: '6 min' },
      { id: 2003, title: 'Structured Contextual Logging with Monolog', xp: 25, duration: '5 min' },
      { id: 2004, title: 'Production Monitoring with Sentry & Distributed Tracing', xp: 30, duration: '6 min' },
    ],
  },
];

export const ACHIEVEMENTS = [
  {
    id: 1,
    key: 'first_steps',
    name: 'First Steps',
    description: 'Complete your first Laravel lesson',
    icon: '🐣',
    rarity: 'common',
    color: '#10b981',
  },
  {
    id: 2,
    key: 'on_fire',
    name: 'On Fire',
    description: 'Reach a 7-day learning streak',
    icon: '🔥',
    rarity: 'rare',
    color: '#f59e0b',
  },
  {
    id: 3,
    key: 'quick_learner',
    name: 'Quick Learner',
    description: 'Complete 3 lessons in a single day',
    icon: '🧠',
    rarity: 'common',
    color: '#3b82f6',
  },
  {
    id: 4,
    key: 'perfect_score',
    name: 'Flawless Victory',
    description: 'Score 100% on any interactive challenge on first attempt',
    icon: '💯',
    rarity: 'rare',
    color: '#ec4899',
  },
  {
    id: 5,
    key: 'db_architect',
    name: 'Database Architect',
    description: 'Master schema design & migrations in Module 5',
    icon: '🗄️',
    rarity: 'epic',
    color: '#8b5cf6',
  },
  {
    id: 6,
    key: 'api_builder',
    name: 'REST Champion',
    description: 'Construct your first full CRUD API',
    icon: '🔗',
    rarity: 'epic',
    color: '#06b6d4',
  },
  {
    id: 7,
    key: 'night_owl',
    name: 'Night Owl',
    description: 'Code and level up late at night',
    icon: '🌙',
    rarity: 'common',
    color: '#6366f1',
  },
  {
    id: 8,
    key: 'speed_demon',
    name: 'Speed Demon',
    description: 'Complete a challenge in under 45 seconds',
    icon: '⚡',
    rarity: 'rare',
    color: '#eab308',
  },
  {
    id: 9,
    key: 'full_stack_falcon',
    name: 'Full-Stack Falcon',
    description: 'Complete all 12 modules and graduate to full-stack engineer',
    icon: '🦅',
    rarity: 'legendary',
    color: '#f43f5e',
  },
];

export const FLUTTER_TIPS = [
  'Remember: In Flutter you write `class User { ... fromJson() }`. In Laravel, Eloquent models map to tables automatically — no serialization boilerplate!',
  'Dio interceptors on mobile are just like Laravel Middleware on the server: they catch the request before it proceeds.',
  'When your Flutter app receives a 422 Unprocessable Entity, Laravel is telling you exactly which form fields failed validation.',
  'Eloquent relationships like `hasMany` solve the problem of making 5 separate HTTP calls from Flutter — eager load them in one clean query!',
  'Think of `php artisan` as Flutter\'s build_runner, but it executes in milliseconds without freezing your terminal.',
];
